# Generated by Django 5.1.7 on 2025-03-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Animation', 'Animation'), ('Game', 'Game'), ('Web Development', 'Web Development'), ('Video', 'Video'), ('Documentary', 'Documentary'), ('Creative Art', 'Creative Art')], max_length=50)),
                ('github_link', models.CharField(blank=True, max_length=255, null=True)),
                ('media_link', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectSDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'project_sdgs',
            },
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('sdg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdg_number', models.IntegerField(unique=True)),
                ('sdg_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'sdgs',
                'ordering': ['sdg_number'],
            },
        ),
    ]
