# Generated by Django 5.1.7 on 2025-03-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.studentteam'),
        ),
        migrations.AddField(
            model_name='projectsdg',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='sdg',
            name='projects',
            field=models.ManyToManyField(related_name='sdgs', through='projects.ProjectSDG', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectsdg',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sdg'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsdg',
            unique_together={('project', 'sdg')},
        ),
    ]
