
# Generated by Django 5.1.7 on 2025-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_populate_sdgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='List of project features as bullet points (stored as JSON)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
