# Generated by Django 5.1.7 on 2025-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_admin_remarks_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdg',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='sdgs',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectSDG', to='projects.sdg'),
        ),
        migrations.AddField(
            model_name='sdg',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdg',
            name='sdg_name',
            field=models.CharField(max_length=255),
        ),
    ]
