# Generated by Django 5.1.4 on 2025-04-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_sdg_projects_project_sdgs_sdg_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Applications', 'Web Applications'), ('Games', 'Games'), ('Animations', 'Animations'), ('Videos', 'Videos'), ('Documentaries', 'Documentaries'), ('Digital Art', 'Digital Art'), ('Mobile Apps', 'Mobile Apps'), ('Data Visualizations', 'Data Visualizations')], max_length=50),
        ),
    ]
