# Generated by Django 5.1.4 on 2025-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Games', 'Games'), ('Animations', 'Animations'), ('Web Applications', 'Web Applications'), ('Mobile Apps', 'Mobile Apps'), ('Digital Art', 'Digital Art'), ('Videos', 'Videos'), ('Documentaries', 'Documentaries'), ('Data Visualizations', 'Data Visualizations')], max_length=50),
        ),
    ]
